<?php

namespace CrazyCodeGen\Tests\Definition\Definitions\Structures\ClassDefScenarios;

use CrazyCodeGen\Common\Enums\VisibilityEnum;
use CrazyCodeGen\Common\Exceptions\NoValidConversionRulesMatchedException;
use CrazyCodeGen\Common\Traits\FlattenFunction;
use CrazyCodeGen\Definition\Definitions\Contexts\ThisContext;
use CrazyCodeGen\Definition\Definitions\Structures\ClassDef;
use CrazyCodeGen\Definition\Definitions\Structures\MethodDef;
use CrazyCodeGen\Definition\Definitions\Structures\PropertyDef;
use CrazyCodeGen\Definition\Definitions\Types\ClassTypeDef;
use CrazyCodeGen\Definition\Definitions\Types\StaticTypeSpec;
use CrazyCodeGen\Definition\Definitions\Values\ArrayVal;
use CrazyCodeGen\Definition\Expressions\Operations\NewOp;
use CrazyCodeGen\Definition\Expressions\Operations\ReturnOp;
use CrazyCodeGen\Definition\Expressions\Operators\Assignment\AssignOp;
use CrazyCodeGen\Tests\Common\Formatters\PhpCsFixerFormatter;
use CrazyCodeGen\Rendering\RenderingContext;
use CrazyCodeGen\Rendering\Traits\TokenFunctions;
use PHPUnit\Framework\TestCase;

class ModelBuilderScenarioTest extends TestCase
{
    use TokenFunctions;
    use FlattenFunction;

    /**
     * @throws NoValidConversionRulesMatchedException
     */
    public function testAbilityToGenerateModelHelperFromPreviousInternalFramework(): void
    {
        $baseModelBuilderType = new ClassTypeDef('Internal\TestFramework\MockingFramework\Builders\BaseModelBuilder');
        $taxExemptionCategoryModelType = new ClassTypeDef('internal\Baskets\Models\TaxExemptionCategoryModel');

        $modelProperty = new PropertyDef('model');

        $createModelMethod = (new MethodDef('createModel'))
            ->setVisibility(VisibilityEnum::PROTECTED)
            ->setReturnType($taxExemptionCategoryModelType)
            ->addInstruction(new ReturnOp(new NewOp(
                class: $taxExemptionCategoryModelType,
                arguments: [
                    new ArrayVal([
                        'identifier' => 'stub',
                        'name' => 'stub',
                    ]),
                ],
            )));
        $hstExemptionMethod = (new MethodDef('hstExemption'))
            ->setReturnType(new StaticTypeSpec())
            ->addInstruction(new AssignOp(
                subject: ThisContext::to($modelProperty)->to('identifier'),
                value: 'hst',
            ))
            ->addInstruction(new AssignOp(
                subject: ThisContext::to($modelProperty)->to('name'),
                value: 'HST',
            ))
            ->addInstruction(new ReturnOp(new ThisContext()));
        $getMethod = (new MethodDef('get'))
            ->setReturnType($taxExemptionCategoryModelType)
            ->addInstruction(new ReturnOp(ThisContext::to($modelProperty)));
        $classDef = (new ClassDef('TaxExemptionCategoryModelBuilder'))
            ->setNamespace('Internal\TestFramework\MockingFramework\Builders\ModelBuilders\InternalApi\Baskets\Models')
            ->addImport($baseModelBuilderType)
            ->addImport($taxExemptionCategoryModelType)
            ->setDocBlock([
                'This file was generated using the Symfony command "mock-helpers:generate".',
                'Do not edit this file as the content will be replaced automatically the next time someone will run the generate command.',
                'If you want to learn more about this framework, visit the documentation on Confluence at: https://example.com/wiki/spaces/COPUNIT/pages/4051238915/Mocking+framework.',
            ])
            ->setExtends($baseModelBuilderType)
            ->addMethod($createModelMethod)
            ->addMethod($hstExemptionMethod)
            ->addMethod($getMethod);

        $code = $this->renderTokensToString($classDef->getTokens(new RenderingContext()));
        $newCode = (new PhpCsFixerFormatter())->format($code);

        $this->assertEquals(
            <<<'EOS'
            <?php
            
            namespace Internal\TestFramework\MockingFramework\Builders\ModelBuilders\InternalApi\Baskets\Models;
            
            use Internal\TestFramework\MockingFramework\Builders\BaseModelBuilder;
            use internal\Baskets\Models\TaxExemptionCategoryModel;
            
            /**
             * This file was generated using the Symfony command "mock-helpers:generate".
             *
             * Do not edit this file as the content will be replaced automatically the next
             * time someone will run the generate command.
             *
             * If you want to learn more about this framework, visit the documentation on
             * Confluence at:
             * https://example.com/wiki/spaces/COPUNIT/pages/4051238915/Mocking+framework.
             */
            
            class TaxExemptionCategoryModelBuilder extends BaseModelBuilder
            {
                protected function createModel(): TaxExemptionCategoryModel
                {
                    return new TaxExemptionCategoryModel(['identifier' => 'stub', 'name' => 'stub']);
                }
            
                public function hstExemption(): static
                {
                    $this->model->identifier = 'hst';
                    $this->model->name = 'HST';
                    return $this;
                }
            
                public function get(): TaxExemptionCategoryModel
                {
                    return $this->model;
                }
            }
            
            EOS,
            $newCode,
        );
    }
}
