<?php

namespace CrazyCodeGen\Tests\Definition\Definitions\Structures\Scenarios;

use CrazyCodeGen\Common\Enums\VisibilityEnum;
use CrazyCodeGen\Definition\Definitions\Contexts\ParentContext;
use CrazyCodeGen\Definition\Definitions\Contexts\ThisContext;
use CrazyCodeGen\Definition\Definitions\Structures\ClassDef;
use CrazyCodeGen\Definition\Definitions\Structures\MethodDef;
use CrazyCodeGen\Definition\Definitions\Structures\MultiTypeDef;
use CrazyCodeGen\Definition\Definitions\Structures\ParameterDef;
use CrazyCodeGen\Definition\Definitions\Structures\PropertyDef;
use CrazyCodeGen\Definition\Definitions\Structures\SingleTypeDef;
use CrazyCodeGen\Definition\Definitions\Structures\VariableDef;
use CrazyCodeGen\Definition\Definitions\Values\ArrayVal;
use CrazyCodeGen\Definition\Definitions\Values\ClassRef;
use CrazyCodeGen\Definition\Definitions\Values\StringVal;
use CrazyCodeGen\Definition\Expressions\Instruction;
use CrazyCodeGen\Definition\Expressions\Operations\Call;
use CrazyCodeGen\Definition\Expressions\Operations\Chain;
use CrazyCodeGen\Definition\Expressions\Operations\NewInstance;
use CrazyCodeGen\Definition\Expressions\Operations\ReturnVal;
use CrazyCodeGen\Definition\Expressions\Operators\Assignment\Assign;
use CrazyCodeGen\Definition\Expressions\Structures\Condition;
use CrazyCodeGen\Rendering\Renderers\Contexts\RenderContext;
use CrazyCodeGen\Rendering\Renderers\Rules\RenderingRules;
use CrazyCodeGen\Rendering\Tokens\CharacterTokens\NewLinesToken;
use CrazyCodeGen\Rendering\Tokens\KeywordTokens\NullToken;
use CrazyCodeGen\Rendering\Tokens\Token;
use CrazyCodeGen\Rendering\Traits\TokenFunctions;
use PHPUnit\Framework\TestCase;

class ServiceBuilderScenarioTest extends TestCase
{
    use TokenFunctions;

    public function testAbilityToGenerateTestBuilderClassFromPreviousInternalFramework()
    {
        $baseMockBuilderType = new SingleTypeDef('Internal\TestFramework\MockingFramework\Builders\BaseMockBuilder');
        $mockObjectType = new SingleTypeDef('PHPUnit\Framework\MockObject\MockObject');
        $hookBasketAdapterType = new SingleTypeDef('internal\Baskets\Adapters\HookBasketAdapter');
        $mockedHookBasketAdapterType = new MultiTypeDef(
            types: [$hookBasketAdapterType, $mockObjectType],
            unionTypes: false,
        );

        $constructor = (new MethodDef('__construct'))
            ->addParameterExploded('mock', $mockedHookBasketAdapterType)
            ->addInstruction(new Assign(
                subject: new Chain([new ThisContext(), 'mock']),
                value: new VariableDef('mock'),
            ));
        $getMockedClassesMethod = (new MethodDef('getMockedClasses'))
            ->setReturnType('array')
            ->setStatic(true)
            ->addInstruction(new ReturnVal(
                new ArrayVal([new ClassRef('HookBasketAdapter')])
            ));
        $getServiceMethod = (new MethodDef('getService'))
            ->setReturnType($mockedHookBasketAdapterType)
            ->addInstruction(new ReturnVal(
                new Chain([new ThisContext(), 'mock'])
            ));
        $classDef = (new ClassDef('HookBasketAdapterBuilder'))
            ->setNamespace('Internal\TestFramework\MockingFramework\Builders\ServiceBuilders\InternalApi\Baskets\Adapters')
            ->addImport($mockObjectType)
            ->addImport($baseMockBuilderType)
            ->addImport($hookBasketAdapterType)
            ->setDocBlock([
                'This file was generated using the Symfony command "mock-helpers:generate".',
                'Do not edit this file as the content will be replaced automatically the next time someone will run the generate command.',
                'If you want to learn more about this framework, visit the documentation on Confluence at: https://example.com/wiki/spaces/COPUNIT/pages/4051238915/Mocking+framework.',
            ])
            ->setExtends($baseMockBuilderType)
            ->addMethod($constructor)
            ->addMethod($getMockedClassesMethod)
            ->addMethod($getServiceMethod);

        $rules = new RenderingRules();
        $rules->docBlocks->lineLength = 125;

        $this->assertEquals(
            <<<'EOS'
            namespace Internal\TestFramework\MockingFramework\Builders\ServiceBuilders\InternalApi\Baskets\Adapters;
            
            use PHPUnit\Framework\MockObject\MockObject;
            use Internal\TestFramework\MockingFramework\Builders\BaseMockBuilder;
            use internal\Baskets\Adapters\HookBasketAdapter;
            
            /**
             * This file was generated using the Symfony command "mock-helpers:generate".
             *
             * Do not edit this file as the content will be replaced automatically the next time someone will run the generate command.
             *
             * If you want to learn more about this framework, visit the documentation on Confluence at:
             * https://example.com/wiki/spaces/COPUNIT/pages/4051238915/Mocking+framework.
             */
            class HookBasketAdapterBuilder extends BaseMockBuilder
            {
                public function __construct(HookBasketAdapter&MockObject $mock)
                {
                    $this->mock = $mock;
                }
            
                public static function getMockedClasses(): array
                {
                    return [HookBasketAdapter::class];
                }
            
                public function getService(): HookBasketAdapter&MockObject
                {
                    return $this->mock;
                }
            }
            
            EOS,
            $this->renderTokensToString($classDef->getTokens(new RenderContext(), $rules)),
        );
    }
}
